// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Transaction struct {
	ID        int64
	Sender    pgtype.Int8
	Receiver  pgtype.Int8
	Amount    pgtype.Numeric
	CreatedAt pgtype.Timestamp
}

type Wallet struct {
	ID      int64
	Balance pgtype.Numeric
}
